"""change type of dietentries added_at column

Revision ID: 0e3e1625bd50
Revises: b1ed189aead1
Create Date: 2025-01-18 14:59:07.722576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3e1625bd50'
down_revision: Union[str, None] = 'b1ed189aead1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dietentry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.String(length=24), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('food_id', sa.String(length=32), nullable=True),
    sa.Column('food_amount_in_grams', sa.Float(), nullable=True),
    sa.Column('weigh', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dietentry')
    # ### end Alembic commands ###
