"""fix 500 characters for recipe column

Revision ID: 1c97dcc94f1b
Revises: f2a3d2b86f7a
Create Date: 2025-01-17 15:07:55.254555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c97dcc94f1b'
down_revision: Union[str, None] = 'f2a3d2b86f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauces', sa.Column('recipe', sa.String(length=500), nullable=False))
    op.drop_column('sauces', 'Recipe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauces', sa.Column('Recipe', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('sauces', 'recipe')
    # ### end Alembic commands ###
