"""change ids to int type, introduce foreign key in dietentry table

Revision ID: 3a85062dd2c3
Revises: c39e94e9358f
Create Date: 2025-01-21 15:45:55.318155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a85062dd2c3'
down_revision: Union[str, None] = 'c39e94e9358f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('distance_in_kilometers', sa.Float(), nullable=True))
    op.alter_column('dietentry', 'id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dietentry', 'food_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'dietentry', 'dishes', ['food_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dietentry', type_='foreignkey')
    op.alter_column('dietentry', 'food_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('dietentry', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('dietentry', 'distance_in_kilometers')
    # ### end Alembic commands ###
