"""added table sauces

Revision ID: 6021593f4c4c
Revises: 4839a7b6d5b9
Create Date: 2025-01-16 19:21:16.949311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6021593f4c4c'
down_revision: Union[str, None] = '4839a7b6d5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sauces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('saturated_fat', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('simple_sugars', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('salt', sa.Float(), nullable=False),
    sa.Column('ingr1_id', sa.String(length=32), nullable=False),
    sa.Column('ingr1_amount', sa.Float(), nullable=False),
    sa.Column('ingr2_id', sa.String(length=32), nullable=False),
    sa.Column('ingr2_amount', sa.Float(), nullable=False),
    sa.Column('ingr3_id', sa.String(length=32), nullable=True),
    sa.Column('ingr3_amount', sa.Float(), nullable=True),
    sa.Column('ingr4_id', sa.String(length=32), nullable=True),
    sa.Column('ingr4_amount', sa.Float(), nullable=True),
    sa.Column('final_weigh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingr1_id'], ['raws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingr2_id'], ['raws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingr3_id'], ['raws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingr4_id'], ['raws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sauces')
    # ### end Alembic commands ###
