"""change column name in dietentries table: weigh -> weight

Revision ID: 832672525a01
Revises: 0e3e1625bd50
Create Date: 2025-01-18 15:14:06.667159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '832672525a01'
down_revision: Union[str, None] = '0e3e1625bd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('weight', sa.Float(), nullable=True))
    op.drop_column('dietentry', 'weigh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('weigh', mysql.FLOAT(), nullable=True))
    op.drop_column('dietentry', 'weight')
    # ### end Alembic commands ###
