"""change ids to int type, introduce foreign key in dietentry table

Revision ID: 9029c9633acf
Revises: 3a85062dd2c3
Create Date: 2025-01-21 15:47:57.949193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9029c9633acf'
down_revision: Union[str, None] = '3a85062dd2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dietentry', 'id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dietentry', 'food_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'dietentry', 'dishes', ['food_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dietentry', type_='foreignkey')
    op.alter_column('dietentry', 'food_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('dietentry', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
