"""change weight column type to float

Revision ID: 9141530d2e6d
Revises: d6dba7a7b0cc
Create Date: 2025-01-18 19:50:06.372369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9141530d2e6d'
down_revision: Union[str, None] = 'd6dba7a7b0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dietentry', 'weight_in_kilograms',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dietentry', 'weight_in_kilograms',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
