"""restore final amount to sauces table

Revision ID: b1ed189aead1
Revises: 1aaabe131dbb
Create Date: 2025-01-17 18:06:40.953385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ed189aead1'
down_revision: Union[str, None] = '1aaabe131dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauces', sa.Column('final_amount_in_grams', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sauces', 'final_amount_in_grams')
    # ### end Alembic commands ###
