"""Init

Revision ID: bd563b4e21e5
Revises: 
Create Date: 2025-02-13 13:24:41.116012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd563b4e21e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('saturated_fat', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('simple_sugars', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('salt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_at', sa.Date(), nullable=True),
    sa.Column('organizer_name', sa.String(length=50), nullable=True),
    sa.Column('event_name', sa.String(length=50), nullable=True),
    sa.Column('kawanarajd', sa.Boolean(), nullable=True),
    sa.Column('coffees_served', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dietentry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_amount_in_grams', sa.Float(), nullable=True),
    sa.Column('weight_in_kilograms', sa.Float(), nullable=True),
    sa.Column('distance_in_kilometers', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('dietentry')
    op.drop_table('events')
    op.drop_table('dishes')
    # ### end Alembic commands ###
