"""change column name in dietentries table: weight -> weight_in_kilograms and column type change

Revision ID: c1b617f514a6
Revises: 832672525a01
Create Date: 2025-01-18 15:18:42.301501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1b617f514a6'
down_revision: Union[str, None] = '832672525a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('5', sa.NullType(), nullable=True))
    op.drop_column('dietentry', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('weight', mysql.FLOAT(), nullable=True))
    op.drop_column('dietentry', '5')
    # ### end Alembic commands ###
