"""add table events

Revision ID: c309bea3ba38
Revises: 0a52f6f2f908
Create Date: 2025-01-22 10:47:32.362622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c309bea3ba38'
down_revision: Union[str, None] = '0a52f6f2f908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_at', sa.Date(), nullable=True),
    sa.Column('organizer_name', sa.String(length=50), nullable=True),
    sa.Column('event_name', sa.String(length=50), nullable=True),
    sa.Column('kawanarajd', sa.Boolean(), nullable=True),
    sa.Column('coffees_issued', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
