"""change column name in dietentries table: weight -> weight_in_kilograms and column type change

Revision ID: d6dba7a7b0cc
Revises: c1b617f514a6
Create Date: 2025-01-18 15:22:11.528718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6dba7a7b0cc'
down_revision: Union[str, None] = 'c1b617f514a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('weight_in_kilograms', sa.String(length=5), nullable=True))
    op.drop_column('dietentry', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dietentry', sa.Column('weight', mysql.FLOAT(), nullable=True))
    op.drop_column('dietentry', 'weight_in_kilograms')
    # ### end Alembic commands ###
