"""rename column final_weigh to final_amount

Revision ID: dfc6c5a4fc01
Revises: 97c2b0524723
Create Date: 2025-01-17 16:04:53.555233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfc6c5a4fc01'
down_revision: Union[str, None] = '97c2b0524723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauces', sa.Column('final_amount', sa.Float(), nullable=False))
    op.drop_column('sauces', 'final_weigh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauces', sa.Column('final_weigh', mysql.FLOAT(), nullable=False))
    op.drop_column('sauces', 'final_amount')
    # ### end Alembic commands ###
