"""change events table column name: coffees_issued -> coffees_served

Revision ID: e4af93a12409
Revises: c309bea3ba38
Create Date: 2025-01-22 11:04:26.857544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4af93a12409'
down_revision: Union[str, None] = 'c309bea3ba38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
